# Build YAML
format: 1

repo: test-ioc
organization: ad-build-test

# Build Script for building the component
build: build.sh

# Environments this app runs on
environments:
  - rocky9
  - rhel7

# dependencies this app needs built
# component: tag name
dependencies:
  - epics-base: R7.0.8
  - asyn: R4.39-1.0.1

# Python packages list
python: requirements.txt
